### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by TaniaTenorio** [sauzy34/react-native-multi-selectbox#10]
I get this error on iOS
![image](https://user-images.githubusercontent.com/51387597/78410812-c0fef780-75ca-11ea-92f6-5accb101ef80.png)

**Comment by sauzy34** [comment]
> I get this error on iOS
> ![image](https://user-images.githubusercontent.com/51387597/78410812-c0fef780-75ca-11ea-92f6-5accb101ef80.png)

You need to install [styled-components](https://www.npmjs.com/package/styled-components)
