### ISSUE TITLE
Change Selected option label text color

### ISSUE THREAD

**Issue by quisen** [sauzy34/react-native-multi-selectbox#13]
Hello! 

Is it possible to change the default color of the selected option label?

Thanks!

I want to be able to change these colors:
```javascript
                <Text style={{ fontSize: 17, color: isEmpty(value.item) ? 'rgba(60, 60, 67, 0.3)' : '#000' }}>
                  {capitalize(value.item) || label}
                </Text>
```

**Comment by sauzy34** [comment]
Hi @quisen. I'll be releasing a new version tonight, having capabilities of changing styles.

**Comment by sauzy34** [comment]
You can use `selectedItemStyle `

**Comment by priyanov101999** [comment]
selectedItemStyle isnt working.Im using verion 1.5.0
