### ISSUE TITLE
VirtualizedLists should never be nested inside plain ScrollViews

### ISSUE THREAD

**Issue by m0w4hhed** [sauzy34/react-native-multi-selectbox#17]
This warning appears when I use your sample code, I think you should fix it for better performance

**Comment by rayasrahiman** [comment]
How do we change the colour of drop down arrow, search icon, and add button

**Comment by sauzy34** [comment]
> How do we change the colour of drop down arrow, search icon, and add button

https://www.npmjs.com/package/react-native-multi-selectbox/v/1.4.6

Use these props & for more understanding read the latest docs
- arrowIconColor
- searchIconColor
- toggleIconColor

**Comment by rayasrahiman** [comment]
> > How do we change the colour of drop down arrow, search icon, and add button
> 
> https://www.npmjs.com/package/react-native-multi-selectbox/v/1.4.6
> 
> Use these props & for more understanding read the latest docs
> 
> * arrowIconColor
> * searchIconColor
> * toggleIconColor

Thanks much.

**Comment by bmartinezg** [comment]
Hello! Is this issue fixed? I get the same error when I add the component into a scrollview
