### ISSUE TITLE
Toggle isn't working

### ISSUE THREAD

**Issue by ritzblogs** [sauzy34/react-native-multi-selectbox#24]
With the same example for multiselect the addcircle doesn't change to deletecircle icon and the value for checked always remains false.

**Comment by sauzy34** [comment]
@ritzblogs Could you share on which platform(iOS/Android) you're facing this issue?
The example code seems to be working for me. If you can share your JSX code block or the repository, I can figure out what could be the issue.

**Comment by rayasrahiman** [comment]
Multi select on Android device not scrolling the list of options whereas in iOS it does scroll
