### ISSUE TITLE
Add props for arrowIconColor, searchIconColor, toggleIconColor

### ISSUE THREAD

**Issue by sauzy34** [sauzy34/react-native-multi-selectbox#25]

**Comment by rayasrahiman** [comment]
Not able to implement any colours to it. It's still showing the default colour.

**Comment by rayasrahiman** [comment]
> Not able to implement any colours to it. It's still showing the default colour.

arrowIconColor, searchIconColor, toggleIconColor Props aren't shown

**Comment by rayasrahiman** [comment]
> Not able to implement any colours to it. It's still showing the default colour.

In iOS platform in Android platform the colour is shown as I'm using expo

**Comment by rayasrahiman** [comment]
> Not able to implement any colours to ios platform but these props works well for Android. On IOS It's still showing the default colour. I'm using expo

It's showing up on ios right now thanks
