### ISSUE TITLE
How to hide the horizontal scroll bar on multi select when there's alot of selected labels?

### ISSUE THREAD

**Issue by rayasrahiman** [sauzy34/react-native-multi-selectbox#26]

**Comment by sauzy34** [comment]
Please share the screenshot & the platform you're using.

**Comment by rayasrahiman** [comment]
> Please share the screenshot & the platform you're using.

Yeah sure here's the screenshot for it the marked one scroll bar below the labels wanted to hide it.
![89118D5A-BF13-4B45-99A6-EBAC2A67C415](https://user-images.githubusercontent.com/58700409/100409549-2b046980-3092-11eb-9844-80c3bc001712.jpeg)

**Comment by rayasrahiman** [comment]
> Please share the screenshot & the platform you're

**Comment by rayasrahiman** [comment]
> Please share the screenshot & the platform you're using.

Yeah sure here's the screenshot the marked one scroll bar below label 
![A4DE34C1-33FD-4D49-B5DE-C8D7C3C09BE8](https://user-images.githubusercontent.com/58700409/100409735-aa923880-3092-11eb-97ef-3d4ad9dbe3a7.jpeg)

**Comment by miguel-martinez-6661** [comment]
Why do you close this issue without an answer? Is there any way to do this?
