### ISSUE TITLE
It would be nice if we could have an option to edit the colour of search input placeholder of the marked one

### ISSUE THREAD

**Issue by rayasrahiman** [sauzy34/react-native-multi-selectbox#27]
![2043A627-6E2F-4473-936B-BAF28B80BD2F](https://user-images.githubusercontent.com/58700409/100410019-723f2a00-3093-11eb-918e-22eb3038840a.jpeg)

**Comment by rayasrahiman** [comment]
This was on ios platform but on Android platform it does show white colour it would be nice if we could change the colour of the text

**Comment by Cwadmail** [comment]
I'm still confused how to change the placeholder. I tried `inputFilterStyle={{ color: "#A5ADB7", fontSize: 15, placeholderTextColor: "#A5ADB7" }}` but that only changed the text when I'm typing. Otherwise the placeholder text is still black.
