### ISSUE TITLE
Options list not scrolling inside scrollview

### ISSUE THREAD

**Issue by shani293** [sauzy34/react-native-multi-selectbox#51]

**Comment by ashrafayad** [comment]
Solution worked for me:

- copy this package code and put the code into your project files and import it
- open react-native-multi-selectbox/src/index.js
- find **<FlatList** code and replace it with **<FlatList nestedScrollEnabled**
- done

**Comment by sauzy34** [comment]
@shani293 Use `listOptionProps` & you can add your desired props for the options list.

**Comment by internetammo** [comment]
like this works for me
`<ScrollView nestedScrollEnabled = {true}>
      <SelectBox
        listOptionProps={{ nestedScrollEnabled: true }}`
