### ISSUE TITLE
Making options text full width of parent

### ISSUE THREAD

**Issue by teo-jun-xiong** [sauzy34/react-native-multi-selectbox#52]
Can I check how do I make it so that the option takes up 100% of the parent, or 100% subtracting the width of the SVG? I tried `flex: 1`, `width: '100%'` but neither worked. 

The rationale is so that the user can press anywhere along the container to select the option, rather than having to press on the text.

**Comment by sauzy34** [comment]
@teo-jun-xiong try `flexGrow: 1`, otherwise share sample code.
