### ISSUE TITLE
Remove border bottom line

### ISSUE THREAD

**Issue by bmartinezg** [sauzy34/react-native-multi-selectbox#56]
Is there any way to hide or remove the border bottom of the selectable container?

<img width="281" alt="Captura de pantalla 2021-08-08 a las 20 03 44" src="https://user-images.githubusercontent.com/36212752/128641323-31e0e782-5a76-474c-9c19-56ff146ce98b.png">

**Comment by sauzy34** [comment]
@bmartinezg Use `optionContainerStyle` to override the style.
